# This Action is taken from as1100k/bevy-discord -> CI.yml

name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.rs"
      - "**.toml"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Currently there are no tests, so ignore it
  #  
  # Run cargo test
#   test:
#     name: Test Suite
#     runs-on: ubuntu-latest
#     timeout-minutes: 30
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v4
#       - name: Install stable toolchain
#         uses: rs-workspace/rust-toolchain@v0.2.0
#       - name: Install Dependencies
#         run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
#       - name: Run cargo test
#         run: cargo test --tests

  # Run cargo clippy
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: rs-workspace/rust-toolchain@v0.2.0
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run clippy
        run: cargo clippy

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: rs-workspace/rust-toolchain@v0.2.0
      - name: Run cargo fmt
        run: cargo fmt --all -- --check